export enum Keys {
  Register = "register",
  Login = "login",
  Refresh = "refresh",
  UpdateAccount = "updateAccount",
  ChangePassword = "changePassword",
  ForgotPassword = "forgotPassword",
  ResetPassword = "resetPassword",
  GetWorkspaces = "getWorkspaces",
  GetWorkspace = "getWorkspace",
  PostWorkspaces = "postWorkspaces",
  PatchWorkspaces = "patchworkspaces",
  GetProjects = "getProjects",
  GetProject = "getProject",
  CreateProject = "createProject",
  GetBoards = "getBoards",
  GetBoard = "getBoard",
  CreateBoard = "createBoard",
  GetMembers = "getmembers",
  GetTasks = "getTasks",
  CreateTask = "createTask",
  GetAssignees = "getAssignee"
}
